# Generated by Django 5.2 on 2025-05-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='event_type',
            field=models.CharField(choices=[('Work', 'Work'), ('School', 'School'), ('Other', 'Other')], default='Work', max_length=10),
        ),
    ]
