# Generated by Django 5.2 on 2025-05-01 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_workschedule_event_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workschedule',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='workschedule',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
            preserve_default=False,
        ),
    ]
