# Generated by Django 5.2 on 2025-05-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_rename_date_workschedule_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='event_type',
            field=models.CharField(choices=[('Work', 'Work'), ('School', 'School'), ('Drill', 'Drill'), ('Other', 'Other')], default='Work', max_length=10),
        ),
    ]
